[package]
name = "sapio-data-repr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jsonschema-valid = "0.5.1"
schemars = "0.8.11"
serde = "1.0.147"
serde_json = "1.0.87"
